### ISSUE TITLE
Searching using integer values causes error

### ISSUE THREAD

**Issue by azuraji** [ketho-wow/LargerMacroIconSelection#3]
Not sure if it's supported or not (but would be nice); I'd like to search using an integer value, e.g. the TextureID of an icon.

This gives me a LUA error though:

```lua
7x ...rgerMacroIconSelection/Mainline/IconDataProvider.lua:31: attempt to concatenate local 'texture' (a nil value)
[string "@LargerMacroIconSelection/Mainline/IconDataProvider.lua"]:31: in function <...rgerMacroIconSelection/Mainline/IconDataProvider.lua:25>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@LargerMacroIconSelection/Mainline/LargerMacroIconSelection.lua"]:83: in function <...oIconSelection/Mainline/LargerMacroIconSelection.lua:80>
```

![image](https://user-images.githubusercontent.com/72912613/202934400-1f7cdb71-8452-451f-97e9-66a05f39a4f5.png)

**Comment by Ketho** [comment]
I suppose you mean searching by index instead of a FileID/TextureID. That's not supported since the index for a specific icon can be different between each class and the macro / equipment manager.

It does support searching by FileID though.

![image](https://user-images.githubusercontent.com/1073877/202938999-ca2466c8-e287-4880-ac0f-011367aaf1c5.png)

![image](https://user-images.githubusercontent.com/1073877/202940087-652acc8b-3997-4f3f-ab50-92ab418844d9.png)

**Comment by azuraji** [comment]
Strange, it was actually indeed FileID/TextureID (_not_ index) I was referring to, but when typing in any numerical values, I'm getting the above error.

UPDATE: It seems to be working for me now.

**Comment by azuraji** [comment]
I think I was able to reproduce it.

1. First I search for a string, e.g. "legion".
2. Then I make a numeric search, e.g. "333".
3. Then I scroll the frame and the error occurs.

**Comment by Ketho** [comment]
Oh thanks for the error report and steps to reproduce, I will look at it
